customerio/customerio-expo-plugin

app.plugin.js, src/helpers/constants/ios.ts, src/helpers/utils/injectCIOPodfileCode.ts, src/ios/withNotificationsXcodeProject.ts, src/types/cio-types.ts
This PR resolves: https://github.com/customerio/issues/issues/8667
It's a simple feature that adds the ability to set `use_frameworks! :linkage => :static` in `NotificationService` to make it compatible with `expo-build-properties`'s `ios.useFrameworks` feature
example:
If we have 
```
[
"expo-build-properties",
{
"ios": {
"useFrameworks": "static"
}
}
]
```
We can set this to avoid an error in `Podfile`
```
ios: {
useFrameworks: 'static', // can be 'static' | 'dynamic' and is not required
pushNotification: {
useRichPush: true,
},
},
```
=> feat: added ability to set use_frameworks to static

src/helpers/utils/codeInjection.ts, src/ios/withNotificationsXcodeProject.ts
https://github.com/customerio/issues/issues/8857
The function that should handle replacements in `.plist` file calls `injectCodeByMultiLineRegex`, which is wrong since this function does not replace the values; it only injects a new value.
This PR adds a new function, `replaceCodeByRegex` which does the replacement correctly
=> fix: fixed info.plist formatting issue

.releaserc.json
The last time we did a release, we had issues with the `CI`, and to get around it, I tried to set the version manually.
I fixed it on `develop`, but the change has not been merged to `alpha` yet, so this PR fixes it on `alpha`
=> fix: update .releaserc.json

.github/workflows/pr_lint.yml
The bot's ability to merge a PR by adding label Ready to merge has been causing issues lately because of the CI authentication problems all mobile repos have been experiencing. I am suggesting to remove the ability for a bot to merge a PR because GitHub now [offers a feature](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) that removes the need for a bot to merge PRs for us
=> ci: remove ci bot merge functionality

src/ios/withNotificationsXcodeProject.ts
Closes: https://github.com/customerio/opsbugs/issues/3083
Fix to prevent expo config plugin to create duplicate folders when running `expo prebuild` multiple times.
=> fix: prevent plugin from creating duplicate folders/groups

package-lock.json, package.json, src/helpers/constants/ios.ts, src/ios/withAppDelegateModifications.ts, src/ios/withNotificationsXcodeProject.ts
Resolves: https://github.com/customerio/issues/issues/8792
This adds support for iOS SDk v2 only.
- Create a new Expo project or use an existing one
- install Expo plugin on this branch
- install the latest RN SDK
- run `expo prebuild --clean`
- install older versions of RN SDK and run `expo prebuild --clean` for each version
- also set `ios.disableNotificationRegistration` to `true` and then `false` and also leave it out
Prebuild should only be successful only on RN SDK with iOS SDK v2 or higher.
RN SDK with iOS SDK lower than v2 should throw an error relating to dependencies.
The code for registering push notification should only be added when `ios.disableNotificationRegistration` is set to `false`
=> feat: support for React Native and iOS SDK v2

README.md
[This customer](https://github.com/customerio/customerio-expo-plugin/issues/61#issuecomment-1511568279) had a great comment regarding our README. Seems as though our README could be out-of-date. 
Since our team focuses our attention on the official SDK docs site, I suggest we simplify this README to point to the SDK docs and remove docs in this file with the risk they will be outdated.
=> docs: remove docs from README because it's behind official docs

src/helpers/constants/ios.ts, src/ios/withAppDelegateModifications.ts
Resolves: https://github.com/customerio/opsbugs/issues/3389
Solution:
Call the following in `didRegisterForRemoteNotificationsWithDeviceToken` delegate method.
[super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken]
Example:
```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
[super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken]
return [pnHandlerObj application:application deviceToken:deviceToken];
}
```
=> fix: expo-notifications compatibility with customerio-expo-plugin

package-lock.json, package.json, src/helpers/constants/ios.ts
Resolves: https://github.com/customerio/issues/issues/9943
- Find the `customerio-expo-plugin` module file path
- Get the root directory of the `customerio-expo-plugin` module
- Navigate to helpers directory, relative to the root directory
- clone a monorepo with an Expo app
- run `yarn link customerio-expo-plugin` on the root directory
- cd into the Expo app directory
- run `yarn add customerio/customerio-expo-plugin#expo-compatibility-for-monorepos`
- run `yarn add customerio-reactnative`
- setup `app.json` /`app.config.js`
- run `expo prebuild --clean`
- `prebuild` should finish without an error
- test the app to see that it builds and runs
=> fix: compatibility for monorepos

src/helpers/constants/ios.ts, src/helpers/utils/injectCIOPodfileCode.ts
Resolves: https://github.com/customerio/customerio-expo-plugin/issues/89
- Added a function to evaluate the relative path to React Native SDK from ios folder
=> fix: path fix for monorepo support

.github/dependabot.yml
This PR modifies our Dependabot configuration to combine updates into a single pull request(hopefully). 
By setting the `open-pull-requests-limit` to 1, we hope that Dependabot will batch multiple updates together, helping to reduce the number of PRs we need to review and merge.
=> chore: set pr limit for dependabot

src/helpers/constants/ios.ts, src/helpers/utils/injectCIOPodfileCode.ts, src/ios/withAppDelegateModifications.ts, src/types/cio-types.ts
I noticed when trying to open [another pr](https://github.com/customerio/customerio-expo-plugin/pull/112), lint has not been run against the main `beta` branch. This made my PR longer then it needed to be because it included a lot of lint fixes in it. 
This PR only includes changes caused by running: 
```
npm install
npm run lint
```
=> refactor: run lint against main branch

src/helpers/native-files/ios/PushService.swift, src/ios/withNotificationsXcodeProject.ts, src/types/cio-types.ts
Enables [this feature being added to iOS SDK](https://github.com/customerio/customerio-ios/pull/407) of configuring the SDK's behavior with automated push click handling. 
By default, pushes will show while app is in the foreground, just like on native iOS. 
Merges into: https://github.com/customerio/customerio-expo-plugin/pull/112
=> feat: show a push while app in foreground

.github/workflows/deploy-sdk.yml, .github/workflows/test.yml, package-lock.json, package.json, src/helpers/constants/ios.ts, src/helpers/native-files/ios/PushService.swift, src/helpers/utils/codeInjection.ts, src/helpers/utils/injectCIOPodfileCode.ts, src/ios/withAppDelegateModifications.ts, src/ios/withNotificationsXcodeProject.ts, src/types/cio-types.ts
Part of: https://github.com/customerio/issues/issues/11289
- Install new feature in iOS SDK of automatic push click handling. This is done by installing a specific version of the RN SDK that has this iOS feature installed. 
- Remove all native iOS code modifications that previously handled push click handling. 
- Add compatibility with `expo-notifications` package. Closes: https://github.com/customerio/customerio-expo-plugin/issues/83
- Deploy native iOS https://github.com/customerio/customerio-ios/pull/403
- Update RN SDK to include ^^^ iOS feature. 
[PR](https://github.com/customerio/docs/pull/1670)
=> feat: automatically handle push click events and increase compatibility with 3rd party push modules

src/ios/withNotificationsXcodeProject.ts
Customerio's Expo config plugin now supports Expo SDK 50.
=> feat: expo 50 upgrade

package.json
Linear ticket: https://linear.app/customerio/issue/MBL-611/plugin-not-found-error-running-expo-doctor-1101
Customers are facing an issue where the `npx expo-doctor` command fails with the error `PLUGIN_NOT_FOUND`
when using the Customer.io Expo plugin. The customers reported that they do have the plugin rightly installed and can find it in `node_modules` but still see the error on running the command hence becoming a blocker for the customers. 
This PR makes sure to include `app.plugin.js` on installing the customerio-expo-plugin in a customer app so that on running npx expo-doctor the file is found and the customers no longer see the error.
Before the fix:
`PluginError: Failed to resolve plugin for module "customerio-expo-plugin" relative to "/Users/xxx/xxxx/xxxxx"`
After the fix: …
=> fix: expo-doctor plugin error

src/ios/withNotificationsXcodeProject.ts
Linear ticket : https://linear.app/customerio/issue/MBL-640/ios-build-error-on-expo-sdk-52-with-react-native-076
A customer reported that their app is not compiling when using the latest versions of Expo and React Native (0.76). The error message indicates a mismatch in the iOS deployment targets. This occurs because the `NotificationServiceExtension` defaults to an iOS deployment target of 13.4 currently, while `CioTracking` now requires a minimum target of 15.1. For a managed workflow, when expo plugin is used, then it is the responsibility of the plugin to set the deployment target for extension as the developer does not have flexibility to manually update the extension target, hence the error is only in the extension.
In our plugin, update the minimum default version from `13.4` to …
=> feat: bumped iOS deployment target for compatibility with Expo SDK 52

.github/workflows/test.yml
This PR adds a new job that runs unit tests for the Expo plugin when changes are pushed to branches and on PRs.
The new job will run all unit tests under the `__tests__` directory in this repository.
=> chore: Add Gituhb action job to run plugin tests

.github/workflows/test.yml
The PR closes the last step of testing mentioned in [this proposal](https://www.notion.so/custio/Tech-Proposal-Reliable-Expo-plugin-1454302f4c2b800fb7d3c30cd76ffbfd?pvs=4#1454302f4c2b8010845cd8598444b77d). To ensure that the generated code for Android and iOS compiles successfully after applying the CIO Expo plugin.
This PR adds two new jobs to the `Test` action:
- `build-android-app`: Builds and compiles the native Android app
- `build-ios-app`: Builds and compiles the native iOS app
=> chore: Create Github Action job that builds native apps (Android, iOS)

test-app/helpers/SdkInit.js, test-app/screens/Dashboard.js, test-app/screens/ProfileAttributeModal.js
In this PR I've added some minor tweaks to the test app to enable full regression for the Expo plugin.
Changes include:
- Adding a `migrationSiteId` to test SDK migrations
- Added modal to add profile attributes
- Added a button to logout
=> chore: Minor tweaks to test app to enable regression

.github/workflows/build-sample-apps.yml, scripts/add-google-service-ios.rb, test-app/app.json, test-app/fastlane/Fastfile, test-app/fastlane/Gymfile, test-app/fastlane/Matchfile, test-app/files/GoogleService-Info.plist
This PR adds a job to build and publish the Expo iOS test app to Firebase.
_I am pretty sure some parts of the flow are not optimal, but this should be good enough to unblock testing and we can optimize the scripts later on._
=> chore: Build and publish iOS test app to Firebase

__tests__/android/__snapshots__/app-manifest.test.js.snap, test-app/App.js, test-app/app.json, test-app/helpers/InAppMessagingListener.js, test-app/screens/Dashboard.js, test-app/screens/NavigationTest.js
This PR setups us two things that can help with testing SDK functionality:
We setup a scheme `expo-test-app://` for out test app that works with `nav-test` page.
The links that can be used are as such: `expo-test-app://nav-test`
You can test by either:
- Using one of the deeplinks above with a push notification
- Added a button that deep links to the test page
Added in-app messaging event listeners to make sure they are working
=> chore: Setup deeplinking and in-app messaging listeners for test app

.github/workflows/test.yml, .gitignore, local-development-readme.md, scripts/build-all.sh, scripts/install-plugin-tarball.sh, scripts/setup-test.sh, test-app/package-lock.json, test-app/package.json
part of [MBL-541](https://linear.app/customerio/issue/MBL-541/expo-user-agent)
Currently, the plugin is added as relative path dependency, causing path resolution issues in post-install scripts. These scripts rely on locating our React Native package in `node_modules`, but relative path setup fails to meet this expectation. This made testing iOS user agent changes a bit challenging. So I switched to tarball dependency, matching what we already do in our React Native apps. It resolves this issue by packaging the plugin as a final version that works fine with existing scripts without changing anything in plugin.
- Added script to install and update the plugin dependency as a tarball for test app
- Updated README and package files to simplify running new scripts
=> chore: update test app to use tarball plugin dependency

package-lock.json, package.json
Bumping SDK version to 2.0.0-beta.0
=> chore: Bumping SDK version to 2.0.0-beta.0

.github/workflows/unpublish-npm-version.yml
This PR introduces a workflow to unpublish plugin versions that we might have mistakenly published.
=> chore: Create workflow to unpublish unwanted plugin npm versions

__tests__/ios/AppDelegate-header.test.js, __tests__/ios/AppDelegate-impl.test.js, __tests__/ios/PushService-swift.test.js, __tests__/ios/__snapshots__/AppDelegate-impl.test.js.snap, __tests__/ios/__snapshots__/PodFile.test.js.snap, scripts/add-google-service-ios.rb, test-app/app.json, test-app/fastlane/Fastfile, test-app/fastlane/Gymfile, test-app/package-lock.json
part of: [MBL-742](https://linear.app/customerio/issue/MBL-742/has-easy-to-understand-app-name)
- Renamed app from `Expo Test App` to `Expo`
- Lock file updates
Please refer to linked ticket for more details about these changes.
**Launcher**
_iOS_
_Android_
=> chore: update sample app name

__tests__/android/__snapshots__/app-gradle-build.test.js.snap, __tests__/android/__snapshots__/app-manifest.test.js.snap, package-lock.json, test-app/app.json, test-app/fastlane/Appfile, test-app/fastlane/Fastfile, test-app/files/GoogleService-Info.plist, test-app/files/google-services.json, test-app/package-lock.json
This PR does two main things:
- Change native apps IDs for Android and iOS to `io.customer.testbed.expo` and `io.customer.testbed.expo.apn` respectively
- Publishes test apps to a separate Firebase App Distribution apps
=> chore: Update test apps Firebase App Distribution app

.github/workflows/build-sample-apps.yml, test-app/fastlane/Fastfile
part of: [MBL-710](https://linear.app/customerio/issue/MBL-710/single-app-per-platform-distributed-to-firebase)
- Updated `Build Sample Apps` action to push sample app to relevant channels
- Modified `get_build_test_groups` lane to decouple from GitHub and accept arguments for passing Firebase distribution groups when distributing sample apps
Please refer to linked ticket for detailed expectations regarding channel distribution.
=> chore: update sample app groups

.github/workflows/reusable_build_sample_apps.yml, test-app/helpers/BuildMetadata.js, test-app/screens/Dashboard.js
closes: [MBL-929](https://linear.app/customerio/issue/MBL-929/bug-expo-testbed-not-all-build-info-is-showing-properly)
- Fixed missing `app.json` updates in iOS sample app workflow
- Updated build info formatting to display one item per line, preventing UI breaks
- Added scroll support to `Dashboard` screen to ensure UI adapts properly to different screen sizes
| Before | After (with scroll) |
| - | - |
| ![Screenshot 2025-02-17 at 1 21 15 PM](https://github.com/user-attachments/assets/1b50cc05-f22e-4e8d-915c-4b3e7dc99c2a) | ![Screenshot 2025-02-17 at 2 09 07 PM](https://github.com/user-attachments/assets/a0b6f491-1b6b-4b5b-8593-832d741c6a6a) |
=> chore: fix test sample app ui for ios

.github/workflows/reusable_build_sample_apps.yml, scripts/applyLocalEnvValues.js, test-app/fastlane/Fastfile
This PR is a quality of life improvement for mobile developers and internal testers by publishing two iOS versions from CI one for APN and FCM, so developers don't have to manually change the config to test both variants.
This PR builds on the approach we used to inject SDK version through `local.env`. An additional property is added to `local.env` for `pushProvider`. This approach could work locally as well, if you create `local.env` locally and populate it with values it will make the correct configuration for you.
=> chore: Build iOS sample app for FCM and APN

plugin/src/helpers/native-files/ios/fcm/PushService.swift
This PR ensures a smooth integration for our customers when using `@react-native-firebase` and configuring CIO push to work with FCM as provider.
Firebase crashes when the call `FirebaseApp.configure()` is done multiple times. Since we cannot be sure if our call will be first, hence adding a check to make sure that `FirebaseApp` is not already configured.
=> chore: Prevent Firebase init call if it's already initialized

__tests__/ios/fcm/GoogleService-InfoCopied.test.js, plugin/src/ios/withGoogleServicesJsonFile.ts
The [ReactNative Firebase dependency](https://rnfirebase.io/) requires `GoogleService-info.plist` to be added to the iOS project.
RN Firebase [doesn't check if the file already exists](https://github.com/invertase/react-native-firebase/blob/d9b7175983f0e7b86747c88fcb522295bedf203b/packages/app/plugin/src/ios/googleServicesPlist.ts#L39) before adding it to the project. Since we cannot depend on customers having ReactNative Firebase to copy the file. Our plugin copies the file.
This PR adds a check at the path where ReactNative Firebase copies the file first before copying it.
=> chore: Prevent GoogleService-info.plist from being double copied

.github/workflows/reusable_build_sample_apps.yml
When we added support for FCM, we have made the iOS app get published twice, once with APN config and once with FCM config
This PR prevents publishing FCM iOS app to public channel to avoid confusing internal stakeholders.
=> chore: Publish testbed app to public channel only for APN and not FCM

.github/workflows/validate-plugin-compatibility.yml, scripts/compatibility/configure-plugin.js, scripts/compatibility/run-compatibility-tests.js, scripts/compatibility/setup-test-app.js, scripts/compatibility/validate-plugin.js, scripts/utils/cli.js, scripts/utils/constants.js
part of: [MBL-967](https://linear.app/customerio/issue/MBL-967/automate-expo-compatibility-checks-on-ci)
- Added workflow to run compatibility tests for our plugin against Expo 51, 52, and latest version to catch future release issues
- Updated compatibility scripts to forward all arguments for improved local testing experience
=> chore: add workflow for compatibility testing

.github/workflows/deploy-sdk.yml, CHANGELOG.md, package.json
`codeclimate/velocity-deploy-action` Github action started [failing](https://github.com/customerio/customerio-expo-plugin/actions/runs/14379532878/job/40319773344), which is blocking SDK release, we are temporarily disabling it to enables releasing
=> fix: Disable Code Climate Velocity Deployment

.github/workflows/build-sample-app-for-sdk-release.yml, .github/workflows/deploy-sdk.yml
Closes: [MBL-1053](https://linear.app/customerio/issue/MBL-1053/auto-create-testbed-releases-for-every-sdk-release)
This PR triggers a sample apps public release build after the SDK has been deployed successfully to NPM so that internal stakeholders always have up to date versions to test with.
=> chore: Trigger sample apps public builds after npm deployment is successful

.gitignore, local-development-readme.md, package-lock.json, package.json, scripts/test-plugin.sh
Please refer to the readme file update included in the PR changes 😇 
TL;DR
You can now use `npm run test-plugin fcm` or `npm run test-plugin apn` to run tests locally.
=> chore: Create convenience script to run unit tests locally

.github/workflows/deploy-sdk.yml
Closes: [MBL-1053](https://linear.app/customerio/issue/MBL-1053/auto-create-testbed-releases-for-every-sdk-release)
I've made a mistake in the previous PR #253, reusable workflows should be called at the job level and not on the step level. Steps can only call custom action and not reusable workflows.
=> chore: Fix Github workflow job triggering public sample app build for SDK releases

__tests__/ios/apn/__snapshots__/AppDelegate-swift.test.js.snap, __tests__/ios/fcm/__snapshots__/AppDelegate-swift.test.js.snap, __tests__/utils.js, package-lock.json, package.json, plugin/src/android/withAndroidManifestUpdates.ts, plugin/src/android/withAppGoogleServices.ts, plugin/src/android/withGistMavenRepository.ts, plugin/src/android/withGoogleServicesJSON.ts, plugin/src/android/withProjectGoogleServices.ts, plugin/src/android/withProjectStrings.ts, plugin/src/helpers/native-files/ios/apn/CioSdkAppDelegateHandler.swift, plugin/src/helpers/native-files/ios/fcm/CioSdkAppDelegateHandler.swift, plugin/src/helpers/utils/fileManagement.ts, plugin/src/ios/utils.ts, plugin/src/ios/withAppDelegateModifications.ts, plugin/src/ios/withCIOIos.ts, plugin/src/ios/withCIOIosSwift.ts, plugin/src/ios/withGoogleServicesJsonFile.ts, plugin/src/ios/withNotificationsXcodeProject.ts, plugin/src/ios/withXcodeProject.ts, test-app/package-lock.json, tsconfig.json
This PR does some minor cleaning and changes based on previous PR comments.
- Enables `verbatimModuleSyntax` TS flag and adjusts imports in TS files to import types explicitly
-  Uses `semver` to check Expo version instead of manual parsing
- Adds snippet for expo-notifications compatibility
- You can use Firebase builds from this branch
- I tested all basic functionality with APN/FCM
- I tested with plugin from this branch working with an Expo 52 app
=> chore: Expo 53 support minor improvements

__tests__/ios/apn/CioSdkAppDelegateHandler-swift.test.js, __tests__/ios/apn/__snapshots__/CioSdkAppDelegateHandler-swift.test.js.snap, __tests__/ios/fcm/CioSdkAppDelegateHandler-swift.test.js, __tests__/ios/fcm/__snapshots__/CioSdkAppDelegateHandler-swift.test.js.snap, package-lock.json, plugin/src/helpers/native-files/ios/apn/CioSdkAppDelegateHandler.swift, plugin/src/helpers/native-files/ios/fcm/CioSdkAppDelegateHandler.swift, test-app/app.json, test-app/package-lock.json
Closes: [MBL-1210](https://linear.app/customerio/issue/MBL-1210/update-wrapper-sdk-with-no-swizzling-system-expo)
This PR migrates the iOS push notification setup from using Swizzling to the non-swizzling approach that uses `App Delegate` wrappers.
- We've initially considered the approach where we wrap Expo's iOS native project generated `AppDelegate` with our own `CioAppDelegateWrapper`
- This approach proved to be risky for two main reasons:
- It could easily conflict with any other plugins trying to do the same
- [Certain parts](https://github.com/expo/expo/blob/9887dd05d691756ee9b70e9b33948da001079655/packages/expo-modules-core/ios/ReactDelegates/ExpoReactDelegate.swift#L26) of the Expo framework expects the main delegate to be of their own types, which is a fair assumption
- This …
=> feat: Use non-swizzling push support solution for iOS

__tests__/android/app-manifest.test.js, package-lock.json, package.json, plugin/src/android/withCIOAndroid.ts, plugin/src/android/withNotificationChannelMetadata.ts, plugin/src/types/cio-types.ts, scripts/compatibility/configure-plugin.js, test-app/app.json, test-app/package-lock.json, test-app/package.json
Closes: [MBL-732](https://linear.app/customerio/issue/MBL-732/expo-enable-setting-android-message-channel-name)
This PR adds configuration for the Customer IO Expo config plugin to allow customers to configure and customize Android push notification messaging channels.
The PR creates a config object under `android` -> `pushNotification`-> `channel` object with optional 3 flags:
- `id`: Custom notification channel ID
- `name`: Custom notification channel name
- `importance`: Custom notification channel importance
I've created a dedicated `pushNotification` object to align with iOS and grouped values under `channel` to explicitly state that all these fields are related
- Added unit test to ensure meta-data is added correctly to native Android project manifest
- Tested that channel is …
=> feat: Add ability to configure messaging channels for local notifications

.github/workflows/test.yml, __tests__/utils/config.test.ts, __tests__/utils/validation.test.ts, api-extractor-output/customerio-expo-plugin.api.md, jest.config.js, plugin/src/android/withCIOAndroid.ts, plugin/src/index.ts, plugin/src/ios/withCIOIos.ts, plugin/src/ios/withNotificationsXcodeProject.ts, plugin/src/types/cio-types.ts, plugin/src/utils/config.ts, plugin/src/utils/validation.ts, test-app/App.js, test-app/app.json, tsconfig.build.json, tsconfig.test.json
part of: [MBL-1316](https://linear.app/customerio/issue/MBL-1316/add-auto-initialization-configuration-option)
- Added `NativeSDKConfig` to support SDK setup via `app.json`
- Added config validation to fail early on misconfigurations during `prebuild`
- Updated test app `app.json` with new config block and added TODO note for future clean-up
- Added `tsconfig.test.json` to fix test import issues
- Updated `jest.config.js` to use test specific TS config
- Updated test workflow to run plugin `utils` tests
```json
{
"android": {
"googleServicesFile": "./files/google-services.json",
"setHighPriorityPushHandler": true,
"pushNotification": {
"channel": {
"id": "cio-expo-id",
"name": "CIO Test",
"importance": 4
}
}
},
"ios": {
"useFrameworks": "static",
"pushNotification": {
"provider": "apn", …
```
=> chore: add auto init config

.github/workflows/reusable_build_sample_apps.yml, package-lock.json, package.json, test-app/app.json, test-app/package-lock.json, test-app/package.json
part of: [MBL-1343](https://linear.app/customerio/issue/MBL-1343/ios-26-xcode-26-beta-build-fails-messagingpush-does-not-conform-to)
Upgraded React Native SDK from `4.7.0` to `4.8.0` which includes following updates:
- Sticky session queue support for iOS
- Public API alignment for iOS
- Xcode 16 beta fixes
- Fixed deep link issues with FCM when using `CioAppDelegateWrapper`
- Updated CI workflows to run `expo prebuild` after `app.json` updates to ensure correct native generation for auto initialization
- Simplified SDK `config` in test app's `app.json` for clarity
=> feat: support for xcode 26 beta

__tests__/utils/__snapshots__/patchPluginNativeCode.test.ts.snap, package-lock.json, package.json, plugin/src/helpers/native-files/ios/CustomerIOSDKInitializer.swift, scripts/compatibility/configure-plugin.js, test-app/helpers/InAppMessagingListener.js, test-app/package-lock.json, test-app/package.json, test-app/screens/Dashboard.js
part of: [MBL-1366](https://linear.app/customerio/issue/MBL-1366/fix-or-remove-react-native-ios-import-dependency-from-expo-plugin-auto)
Resolves compatibility issues caused by importing React Native SDK header (`import customerio_reactnative`) in iOS environment. This change removes the need for importing the header entirely by relying on shared dependency graph and improved event listener setup logic in React Native SDK.
- Handled the case where React Native in app event listener is loaded early (before the SDK is initialized):
- Native initializer retrieves the listener from shared DI graph and sets it directly during SDK initialization
- For more common case where the event listener is loaded later (after UI is ready):
- React Native SDK sets the listener during its in app module …
=> fix: remove react native sdk header import in ios
